# -*- coding: utf-8 -*-
# ==================================================================================================================================
# Copyright (c) 2017 - 2018 Stephen Copplestone and Matthias Sonntag
#
# This file is part of reggie (github.com/reggie-framework/reggie). reggie is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# reggie is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License along with reggie. If not, see <http://www.gnu.org/licenses/>.
# ==================================================================================================================================

# ==================================================================================================================================
# Continuous Integration/Continuous Deployment
# ==================================================================================================================================

spec:
  inputs:
    DO_DEPLOY:
      type: boolean
      description: "Push the master branch to the reggie-framework/reggie repository on github"
      default: false
---
# Official language image. Look for the different tagged releases at:
# > https://hub.docker.com/r/library/python/tags/
image: python:3.14-bookworm

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Templates ("hidden jobs")
# ----------------------------------------------------------------------------------------------------------------------------------------------------
.defaults: &defaults
  # tags: [dockertag]
  # cache:
  #   - *venv_cache
  #   - *pip_cache
  # CI/CD has no dependencies
  dependencies: []

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Define a reusable global before_script with YAML anchors
.global-before-script: &global-before-script
  # Load modules on new boltzplatz reggie
  - export PATH="/var/lib/gitlab-runner/.local/bin:$PATH"
  - module list || true
  # Setup system
  - ulimit -s unlimited
  - python3 -V || true
  # Setup Python virtual environment
  - python -m venv .venv
  - source .venv/bin/activate
  # Install reggie
  - python -m pip install --editable .

# Define a reusable global before_script with YAML anchors
.minimal-before-script: &minimal-before-script
  # Load modules on new boltzplatz reggie
  - export PATH="/var/lib/gitlab-runner/.local/bin:$PATH"
  - module list || true
  # Setup system
  - ulimit -s unlimited
  - python3 -V || true
  # Setup Python virtual environment
  - python -m venv .venv
  - source .venv/bin/activate

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stages
# ----------------------------------------------------------------------------------------------------------------------------------------------------
stages:
  - lint
  - compatibility
  - deploy

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Linter
# ----------------------------------------------------------------------------------------------------------------------------------------------------
ruff:
  extends: .defaults
  stage: lint
  before_script: *minimal-before-script
  script:
    # Install Ruff
    - python -m pip install ruff
    # Ruff linter
    - ruff --version
    - ruff check --config pyproject.toml --preview reggie

ty:
  extends: .defaults
  stage: lint
  before_script: *global-before-script
  script:
    # Install Ty
    - python -m pip install ty
    # Ty type checker
    - ty --version
    - ty check --color always --project reggie

vulture:
  extends: .defaults
  stage: lint
  before_script: *minimal-before-script
  script:
    - python -m pip install vulture
    - vulture --version
    - vulture --config pyproject.toml reggie

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Compatibility
# ----------------------------------------------------------------------------------------------------------------------------------------------------

.compatibility-script: &compatibility-script
  script:
    # Compatibility
    - reggie --help

# Python 3.10 ----------------------------------------------------------------------------------------------------------------------------------------
python:3.10:
  extends: .defaults
  stage: compatibility
  image: python:3.10-bookworm
  before_script: *global-before-script
  <<: *compatibility-script
# Python 3.11 ----------------------------------------------------------------------------------------------------------------------------------------
python:3.11:
  extends: .defaults
  stage: compatibility
  image: python:3.11-bookworm
  before_script: *global-before-script
  <<: *compatibility-script
# Python 3.12 ----------------------------------------------------------------------------------------------------------------------------------------
python:3.12:
  extends: .defaults
  stage: compatibility
  image: python:3.12-bookworm
  before_script: *global-before-script
  <<: *compatibility-script
# Python 3.13 ----------------------------------------------------------------------------------------------------------------------------------------
python:3.13:
  extends: .defaults
  stage: compatibility
  image: python:3.13-bookworm
  before_script: *global-before-script
  <<: *compatibility-script
# Python 3.14 ----------------------------------------------------------------------------------------------------------------------------------------
python:3.14:
  extends: .defaults
  stage: compatibility
  image: python:3.14-bookworm
  before_script: *global-before-script
  <<: *compatibility-script

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Stage "github": Push the master branch to github
# ----------------------------------------------------------------------------------------------------------------------------------------------------
github:
  stage: deploy
  script:
    - if [ "$[[ inputs.DO_DEPLOY ]]" == "false" ]; then exit ; fi
    - rm -rf reggie_github || true ;
    - git clone -b master --single-branch git@piclas.boltzplatz.eu:reggie2.0/reggie2.0.git reggie_github ;
    - cd reggie_github ;
    - git remote add reggie-framework git@github.com-framework-reggie2.0:reggie-framework/reggie.git ;
    - git push --force --follow-tags reggie-framework master ;
  rules:
    - if: $[[ inputs.DO_DEPLOY ]] == true
